version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-reservas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservadb
    ports:
      - "3307:3306"
    volumes:
      - mysql_reservas_data:/var/lib/mysql
    networks:
      - reserva-network

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service-app
    ports:
      - "8761:8761"
    networks:
      - reserva-network
    depends_on:
      - mysql

  user-service:
    build: ./user-service
    container_name: user-service-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-reservas:3306/userdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service-app:8761/eureka/
    networks:
      - reserva-network
    depends_on:
      - mysql
      - discovery-service

  cancha-service:
    build: ./cancha-service
    container_name: cancha-service-app
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-reservas:3306/canchadb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service-app:8761/eureka/
    networks:
      - reserva-network
    depends_on:
      - mysql
      - discovery-service

  horario-service:
    build: ./horario-service
    container_name: horario-service-app
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-reservas:3306/horariodb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service-app:8761/eureka/
    networks:
      - reserva-network
    depends_on:
      - mysql
      - discovery-service

  pago-service:
    build: ./pago-service
    container_name: pago-service-app
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-reservas:3306/pagodb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service-app:8761/eureka/
    networks:
      - reserva-network
    depends_on:
      - mysql
      - discovery-service
      - reserva-service

  recinto-service:
    build: ./recinto-service
    container_name: recinto-service-app
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-reservas:3306/recintosdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service-app:8761/eureka/
    networks:
      - reserva-network
    depends_on:
      - mysql
      - discovery-service
      - user-service 

  notificacion-service:
    build: ./notificacion-service
    container_name: notificacion-service-app
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-reservas:3306/notificaciondb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service-app:8761/eureka/
    networks:
      - reserva-network
    depends_on:
      - mysql
      - discovery-service  
      
  resena-service:
    build: ./resena-service
    container_name: resena-service-app
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-reservas:3306/resenadb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service-app:8761/eureka/
    networks:
      - reserva-network
    depends_on:
      - mysql
      - discovery-service
      - cancha-service
      - user-service
      
  precio-service:
    build: ./precio-service
    container_name: precio-service-app
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-reservas:3306/preciodb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service-app:8761/eureka/
    networks:
      - reserva-network
    depends_on:
      - mysql
      - discovery-service
      - cancha-service


  mantenimiento-service:
    build: ./mantenimiento-service
    container_name: mantenimiento-service-app
    ports:
      - "8090:8090"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service-app:8761/eureka/
    networks:
      - reserva-network
    depends_on:
      - mysql
      - discovery-service

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway-app
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service-app:8761/eureka/
    networks:
      - reserva-network
    depends_on:
      - discovery-service
      - user-service
      - cancha-service
      - horario-service
      - reserva-service
      - pago-service
      - precio-service
      - recinto-service
      - notificacion-service
      - resena-service
      - mantenimiento-service 

volumes:
  mysql_reservas_data:

networks:
  reserva-network:
    driver: bridge