server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**

            - id: cancha-service
              uri: lb://CANCHA-SERVICE
              predicates:
                - Path=/api/canchas/**

            - id: horario-service
              uri: lb://HORARIO-SERVICE
              predicates:
                - Path=/api/horarios/**

            - id: reserva-service
              uri: lb://RESERVA-SERVICE
              predicates:
                - Path=/api/reservas/**
                
            - id: pago-service
              uri: lb://PAGO-SERVICE
              predicates:
                - Path=/api/pagos/**
                
            - id: precio-service
              uri: lb://PRECIO-SERVICE
              predicates:
                - Path=/api/precios/** - id: recinto-service
              uri: lb://RECINTO-SERVICE
              predicates:
                - Path=/api/recintos/**
                
            - id: notificacion-service
              uri: lb://NOTIFICACION-SERVICE
              predicates:
                - Path=/api/notificaciones/** - id: resena-service
              uri: lb://RESENA-SERVICE
              predicates:
                - Path=/api/resenas/** 
            - id: mantenimiento-service
              uri: lb://MANTENIMIENTO-SERVICE
              predicates:
                - Path=/api/mantenimientos/**

            - id: precio-service-docs
              uri: lb://PRECIO-SERVICE
              predicates:
                - Path=/precio-service/v3/api-docs
              filters:
                - RewritePath=/precio-service/v3/api-docs,/v3/api-docs   
                
            - id: recinto-service-docs
              uri: lb://RECINTO-SERVICE
              predicates:
                - Path=/recinto-service/v3/api-docs
              filters:
                - RewritePath=/recinto-service/v3/api-docs,/v3/api-docs    

            - id: notificacion-service-docs
              uri: lb://NOTIFICACION-SERVICE
              predicates:
                - Path=/notificacion-service/v3/api-docs
              filters:
                - RewritePath=/notificacion-service/v3/api-docs,/v3/api-docs   

            - id: user-service-docs
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/v3/api-docs
              filters:
                - RewritePath=/user-service/v3/api-docs,/v3/api-docs
                
            - id: resena-service-docs
              uri: lb://RESENA-SERVICE
              predicates:
                - Path=/resena-service/v3/api-docs
              filters:
                - RewritePath=/resena-service/v3/api-docs,/v3/api-docs
                
            - id: cancha-service-docs
              uri: lb://CANCHA-SERVICE
              predicates:
                - Path=/cancha-service/v3/api-docs
              filters:
                - RewritePath=/cancha-service/v3/api-docs,/v3/api-docs

            - id: horario-service-docs
              uri: lb://HORARIO-SERVICE
              predicates:
                - Path=/horario-service/v3/api-docs
              filters:
                - RewritePath=/horario-service/v3/api-docs,/v3/api-docs

            - id: reserva-service-docs
              uri: lb://RESERVA-SERVICE
              predicates:
                - Path=/reserva-service/v3/api-docs
              filters:
                - RewritePath=/reserva-service/v3/api-docs,/v3/api-docs
                
            - id: pago-service-docs
              uri: lb://PAGO-SERVICE
              predicates:
                - Path=/pago-service/v3/api-docs
              filters:
                - RewritePath=/pago-service/v3/api-docs,/v3/api-docs

            - id: mantenimiento-service-docs
              uri: lb://MANTENIMIENTO-SERVICE
              predicates:
                - Path=/mantenimiento-service/v3/api-docs
              filters:
                - RewritePath=/mantenimiento-service/v3/api-docs,/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Cancha Service
        url: /cancha-service/v3/api-docs
      - name: Horario Service
        url: /horario-service/v3/api-docs
      - name: Reserva Service
        url: /reserva-service/v3/api-docs
      - name: Pago Service
        url: /pago-service/v3/api-docs
      - name: Precio Service
        url: /precio-service/v3/api-docs
      - name: Recinto Service
        url: /recinto-service/v3/api-docs  
      - name: Resena Service
        url: /resena-service/v3/api-docs  
      - name: Mantenimiento Service
        url: /mantenimiento-service/v3/api-docs  

management:
  endpoints:
    web:
      exposure:
        include: health,info